name: Deploy

on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types:
      - completed

jobs:
  deploy-staging:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.27.0'
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.12.0'
      - name: Kube auth (placeholder)
        run: echo "Authenticate to cluster via OIDC here"
      - name: Helm upgrade (staging)
        run: echo "helm upgrade --install pptx charts/pptx -f charts/values-staging.yaml"
      - name: Post-deploy health
        run: echo "curl -f https://staging.example.com/api/v1/health"

